/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.expensetracker;

import com.google.cloud.firestore.Firestore;
import com.google.cloud.firestore.QueryDocumentSnapshot;
import com.google.cloud.firestore.QuerySnapshot;
import java.awt.event.*;
import java.util.concurrent.ExecutionException;
import javax.swing.*;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author sirh9
 */
public class ForgotPassword extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ForgotPassword.class.getName());

    public ForgotPassword() {
        initComponents();
        
        setLocationRelativeTo(null); 
        
        goToLogin.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                navigateToLogin();
            }
        });

        setupPlaceholder(emailText, "Email...");
        setupPasswordFieldPlaceholder(passwordText, "New Password");
        setupPasswordFieldPlaceholder(confirmPasswordText, "Confirm Password");
    }
    
    private void setupPlaceholder(final javax.swing.JTextField textField, final String placeholder) {
        textField.setText(placeholder);
        textField.setForeground(java.awt.Color.GRAY);
        
        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(java.awt.Color.BLACK);
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(java.awt.Color.GRAY);
                }
            }
        });
    }
    
    private void setupPasswordFieldPlaceholder(final JPasswordField passwordField, final String placeholder) {
        passwordField.setText(placeholder);
        passwordField.setForeground(java.awt.Color.GRAY);
        passwordField.setEchoChar((char) 0);

        passwordField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (new String(passwordField.getPassword()).equals(placeholder)) {
                    passwordField.setText("");
                    passwordField.setEchoChar('*'); 
                    passwordField.setForeground(java.awt.Color.BLACK);
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (new String(passwordField.getPassword()).isEmpty()) {
                    passwordField.setText(placeholder);
                    passwordField.setEchoChar((char) 0);
                    passwordField.setForeground(java.awt.Color.GRAY);
                }
            }
        });
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goToLogin = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        forgotPanel = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        resetButton = new javax.swing.JButton();
        emailText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        confirmPasswordText = new javax.swing.JPasswordField();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        goToLogin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        goToLogin.setForeground(new java.awt.Color(255, 255, 255));
        goToLogin.setText("Login");
        getContentPane().add(goToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        logo.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setText("SpendWise ");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        forgotPanel.setOpaque(false);

        heading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setText("Forgot Password");

        resetButton.setBackground(new java.awt.Color(0, 153, 255));
        resetButton.setForeground(new java.awt.Color(255, 255, 255));
        resetButton.setText("Reset Password");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        emailText.setBackground(new java.awt.Color(255, 255, 255));
        emailText.setForeground(new java.awt.Color(0, 0, 0));
        emailText.setText("Email...");
        emailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextActionPerformed(evt);
            }
        });

        passwordText.setBackground(new java.awt.Color(255, 255, 255));
        passwordText.setForeground(new java.awt.Color(0, 0, 0));
        passwordText.setText("jPasswordField1");

        confirmPasswordText.setBackground(new java.awt.Color(255, 255, 255));
        confirmPasswordText.setForeground(new java.awt.Color(0, 0, 0));
        confirmPasswordText.setText("jPasswordField2");

        javax.swing.GroupLayout forgotPanelLayout = new javax.swing.GroupLayout(forgotPanel);
        forgotPanel.setLayout(forgotPanelLayout);
        forgotPanelLayout.setHorizontalGroup(
            forgotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotPanelLayout.createSequentialGroup()
                .addGroup(forgotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(forgotPanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(heading))
                    .addGroup(forgotPanelLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(forgotPanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(forgotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailText, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(passwordText)
                            .addComponent(confirmPasswordText))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        forgotPanelLayout.setVerticalGroup(
            forgotPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(heading)
                .addGap(26, 26, 26)
                .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(confirmPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(resetButton)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(forgotPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 390, 340));

        bgImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\sirh9\\Downloads\\nasa waly bohot khatarnak hn.png")); // NOI18N
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, -80, 1015, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        performPasswordReset(); // TODO add your handling code here:
    }//GEN-LAST:event_resetButtonActionPerformed

    private void emailTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextActionPerformed

    private void performPasswordReset() {
        String email = emailText.getText().trim();
        String newPassword = new String(passwordText.getPassword());
        String confirmPassword = new String(confirmPasswordText.getPassword());

        if (email.isEmpty() || newPassword.isEmpty() || confirmPassword.isEmpty() || email.equals("Email...")) {
            JOptionPane.showMessageDialog(this, "Please fill in all fields.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Email validation regex
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        if (!email.matches(emailRegex)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (!newPassword.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "New passwords do not match.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (newPassword.length() < 6) {
            JOptionPane.showMessageDialog(this, "Password must be at least 6 characters long.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        LoadingDialog.showLoading(this, "Resetting password...");
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                Firestore db = FirebaseService.getFirestore();
                
                // Find user by email
                QuerySnapshot query = db.collection("users").whereEqualTo("email", email).get().get();
                
                if (query.isEmpty()) {
                    throw new Exception("No user found with that email.");
                }
                
                // It should be unique, so just take the first one
                QueryDocumentSnapshot userDoc = query.getDocuments().get(0);
                
                String salt = BCrypt.gensalt();
                String hashedPassword = BCrypt.hashpw(newPassword, salt);
                
                // Update password
                userDoc.getReference().update("password_hash", hashedPassword).get();
                
                return null;
            }

            @Override
            protected void done() {
                try {
                    get();
                    JOptionPane.showMessageDialog(ForgotPassword.this, "Password reset successfully! Please log in.", "Success", JOptionPane.INFORMATION_MESSAGE);
                    navigateToLogin();
                } catch (ExecutionException ex) {
                     if (ex.getCause() != null && ex.getCause() instanceof Exception) {
                         JOptionPane.showMessageDialog(ForgotPassword.this, ex.getCause().getMessage(), "Reset Failed", JOptionPane.ERROR_MESSAGE);
                     } else {
                         JOptionPane.showMessageDialog(ForgotPassword.this, "Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                         logger.log(java.util.logging.Level.SEVERE, "Reset error", ex);
                     }
                } catch (InterruptedException ex) {
                    logger.log(java.util.logging.Level.SEVERE, "Reset interrupted", ex);
                } finally {
                    LoadingDialog.hideLoading();
                }
            }
        };
        worker.execute();
    }
    
    private void navigateToLogin() {
        this.dispose(); 
        new Login().setVisible(true); 
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ForgotPassword().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JPasswordField confirmPasswordText;
    private javax.swing.JTextField emailText;
    private javax.swing.JPanel forgotPanel;
    private javax.swing.JLabel goToLogin;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
}
