/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.expensetracker;

import com.google.cloud.firestore.DocumentSnapshot;
import com.google.cloud.firestore.Firestore;
import java.awt.event.*;
import java.util.concurrent.ExecutionException;
import javax.swing.*;
import org.mindrot.jbcrypt.BCrypt;


/**
 *
 * @author sirh9
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    public Login(){
        initComponents();
        setLocationRelativeTo(null);
        
        goToSignUp.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                navigateToSignUp();
            }
        });

        forgotPassword.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                navigateToForgotPassword();
            }
        });
        
        setupPlaceholder(usernameText, "Username...");
        setupPlaceholder(passwordText,"Password...");
    }
    
    private void setupPlaceholder(final javax.swing.JTextField textField, final String placeholder) {
        textField.setText(placeholder);
        textField.setForeground(java.awt.Color.GRAY);
        
        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(java.awt.Color.BLACK);
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(java.awt.Color.GRAY);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goToSignUp = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        loginButton = new javax.swing.JButton();
        forgotPassword = new javax.swing.JLabel();
        passwordText = new javax.swing.JPasswordField();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        goToSignUp.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        goToSignUp.setForeground(new java.awt.Color(255, 255, 255));
        goToSignUp.setText("Sign Up");
        goToSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToSignUpMouseClicked(evt);
            }
        });
        getContentPane().add(goToSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        logo.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setText("SpendWise ");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        loginPanel.setOpaque(false);

        heading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setText("Login");

        usernameText.setBackground(new java.awt.Color(255, 255, 255));
        usernameText.setForeground(new java.awt.Color(0, 0, 0));
        usernameText.setText("Username...");

        loginButton.setBackground(new java.awt.Color(0, 153, 255));
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });

        forgotPassword.setForeground(new java.awt.Color(0, 0, 0));
        forgotPassword.setText("Forgot Password");

        passwordText.setBackground(new java.awt.Color(255, 255, 255));
        passwordText.setForeground(new java.awt.Color(0, 0, 0));
        passwordText.setText("jPasswordField1");

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loginPanelLayout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(heading)
                .addGap(175, 175, 175))
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(forgotPassword)))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameText, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(passwordText))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(heading)
                .addGap(47, 47, 47)
                .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(loginButton)
                .addGap(18, 18, 18)
                .addComponent(forgotPassword)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 390, 340));

        bgImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\sirh9\\Downloads\\nasa waly bohot khatarnak hn.png")); // NOI18N
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, -80, 1010, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        performLogin();
        // TODO add your handling code here:
    }//GEN-LAST:event_loginButtonActionPerformed

    private void goToSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToSignUpMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_goToSignUpMouseClicked

    private void performLogin() {
        String username = usernameText.getText().trim();
        String password = new String(passwordText.getPassword()); 
        
        if (username.equals("Username...") || password.equals("Password...") || username.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter both username and password.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        LoadingDialog.showLoading(this, "Logging in...");
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                Firestore db = FirebaseService.getFirestore();
                
                DocumentSnapshot doc = db.collection("users").document(username).get().get();
                
                if (doc.exists()) {
                    String storedHash = doc.getString("password_hash");
                    
                    if (storedHash == null) {
                         throw new Exception("User data corrupted (missing password hash).");
                    }
                    
                    if (BCrypt.checkpw(password, storedHash)) {
                         // Login Success - Load categories
                         CategoryModel.loadFromFirestore(db);
                    } else {
                        throw new Exception("Invalid username or password.");
                    }
                } else {
                    throw new Exception("Invalid username or password.");
                }
                
                return null;
            }

            @Override
            protected void done() {
                try {
                    get();
                    JOptionPane.showMessageDialog(Login.this, "Login Successful!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    navigateToHome(username, username);
                } catch (ExecutionException ex) {
                     if (ex.getCause() != null && ex.getCause() instanceof Exception) {
                         JOptionPane.showMessageDialog(Login.this, ex.getCause().getMessage(), "Login Failed", JOptionPane.ERROR_MESSAGE);
                    } else {
                         JOptionPane.showMessageDialog(Login.this, "Login error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                         logger.log(java.util.logging.Level.SEVERE, "Login error", ex);
                     }
                } catch (InterruptedException ex) {
                    logger.log(java.util.logging.Level.SEVERE, "Login interrupted", ex);
                } finally {
                    LoadingDialog.hideLoading();
                }
            }
        };
        worker.execute();
    }
    
    private void navigateToHome(String currentUserId, String currentUserName) {
        this.dispose();
        new HomePage(currentUserId, currentUserName).setVisible(true);
    }
    
    private void navigateToSignUp() {
        this.dispose(); 
        new SignUp().setVisible(true);
    }
    
    private void navigateToForgotPassword() {
        this.dispose(); 
        new ForgotPassword().setVisible(true);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgImage;
    private javax.swing.JLabel forgotPassword;
    private javax.swing.JLabel goToSignUp;
    private javax.swing.JLabel heading;
    private javax.swing.JButton loginButton;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
