/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.expensetracker;

import com.google.cloud.firestore.Firestore;
import com.google.cloud.firestore.QuerySnapshot;
import java.awt.event.*;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.ExecutionException;
import javax.swing.*;
import org.mindrot.jbcrypt.BCrypt;

/**
 *
 * @author sirh9
 */
public class SignUp extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUp.class.getName());

   public SignUp() {
        initComponents();
        
        setLocationRelativeTo(null); 
        
        goToLogin.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                navigateToLogin();
            }
        });

        setupPlaceholder(usernameText, "Username...");
        setupPlaceholder(emailText, "Email..."); 
        setupPlaceholder(passwordText,"Password...");
        setupPlaceholder(ConfirmPasswordText, "Confirm Password...");
    }
   
   private void setupPlaceholder(final javax.swing.JTextField textField, final String placeholder) {
        textField.setText(placeholder);
        textField.setForeground(java.awt.Color.GRAY);
        
        textField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(java.awt.Color.BLACK);
                }
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(java.awt.Color.GRAY);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        goToLogin = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();
        signUpPanel = new javax.swing.JPanel();
        heading = new javax.swing.JLabel();
        usernameText = new javax.swing.JTextField();
        emailText = new javax.swing.JTextField();
        passwordText = new javax.swing.JPasswordField();
        ConfirmPasswordText = new javax.swing.JPasswordField();
        signUpButton = new javax.swing.JButton();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        goToLogin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        goToLogin.setForeground(new java.awt.Color(255, 255, 255));
        goToLogin.setText("Login");
        getContentPane().add(goToLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, -1));

        logo.setFont(new java.awt.Font("Imprint MT Shadow", 1, 48)); // NOI18N
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setText("SpendWise ");
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        signUpPanel.setOpaque(false);

        heading.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        heading.setForeground(new java.awt.Color(255, 255, 255));
        heading.setText("Sign Up");

        usernameText.setBackground(new java.awt.Color(255, 255, 255));
        usernameText.setForeground(new java.awt.Color(0, 0, 0));
        usernameText.setText("Username...");
        usernameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameTextActionPerformed(evt);
            }
        });

        emailText.setBackground(new java.awt.Color(255, 255, 255));
        emailText.setForeground(new java.awt.Color(0, 0, 0));
        emailText.setText("Email...");

        passwordText.setBackground(new java.awt.Color(255, 255, 255));
        passwordText.setForeground(new java.awt.Color(0, 0, 0));
        passwordText.setText("jPasswordField1");

        ConfirmPasswordText.setBackground(new java.awt.Color(255, 255, 255));
        ConfirmPasswordText.setForeground(new java.awt.Color(0, 0, 0));
        ConfirmPasswordText.setText("jPasswordField2");

        signUpButton.setBackground(new java.awt.Color(0, 153, 255));
        signUpButton.setForeground(new java.awt.Color(255, 255, 255));
        signUpButton.setText("Sign Up");
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signUpPanelLayout = new javax.swing.GroupLayout(signUpPanel);
        signUpPanel.setLayout(signUpPanelLayout);
        signUpPanelLayout.setHorizontalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpPanelLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(heading)
                .addGap(175, 175, 175))
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(signUpPanelLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(usernameText, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(emailText, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(passwordText)
                            .addComponent(ConfirmPasswordText))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signUpPanelLayout.setVerticalGroup(
            signUpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signUpPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(heading)
                .addGap(18, 18, 18)
                .addComponent(usernameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(emailText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ConfirmPasswordText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(signUpButton)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(signUpPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 390, 340));

        bgImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\sirh9\\Downloads\\nasa waly bohot khatarnak hn.png")); // NOI18N
        getContentPane().add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(-320, -80, 1015, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signUpButtonActionPerformed
       performSignUp();
       // TODO add your handling code here:
    }//GEN-LAST:event_signUpButtonActionPerformed

    private void usernameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameTextActionPerformed

    private void performSignUp() {

        String username = usernameText.getText().trim();
        String email = emailText.getText().trim();
        
        String password = new String(passwordText.getPassword());
        String confirmPassword = new String(ConfirmPasswordText.getPassword());

        if (username.isEmpty() || username.equals("Username...") || 
            email.isEmpty() || email.equals("Email...") || 
            password.isEmpty() || password.equals("Password...") || 
            confirmPassword.isEmpty() || confirmPassword.equals("Confirm Password...")) {
            
            JOptionPane.showMessageDialog(this, "All fields are required.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Email validation regex
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\.[a-zA-Z0-9_+&*-]+)*@(?:[a-zA-Z0-9-]+\\.)+[a-zA-Z]{2,7}$";
        if (!email.matches(emailRegex)) {
            JOptionPane.showMessageDialog(this, "Please enter a valid email address.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (!password.equals(confirmPassword)) {
            JOptionPane.showMessageDialog(this, "Passwords do not match.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if (password.length() < 6) {
            JOptionPane.showMessageDialog(this, "Password must be at least 6 characters long.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        SwingWorker<Void, Void> worker = new SwingWorker<Void, Void>() {
            @Override
            protected Void doInBackground() throws Exception {
                Firestore db = FirebaseService.getFirestore();
                
                // Check if username exists
                QuerySnapshot usernameQuery = db.collection("users").whereEqualTo("username", username).get().get();
                if (!usernameQuery.isEmpty()) {
                    throw new Exception("Username already in use.");
                }
                
                // Check if email exists
                QuerySnapshot emailQuery = db.collection("users").whereEqualTo("email", email).get().get();
                if (!emailQuery.isEmpty()) {
                    throw new Exception("Email already in use.");
                }
                
                String salt = BCrypt.gensalt();
                String hashedPassword = BCrypt.hashpw(password, salt);
                
                Map<String, Object> userData = new HashMap<>();
                userData.put("username", username);
                userData.put("email", email);
                userData.put("password_hash", hashedPassword);
                
                // Use username as the document ID
                db.collection("users").document(username).set(userData).get();
                
                return null;
            }

            @Override
            protected void done() {
                try {
                    get();
                    JOptionPane.showMessageDialog(SignUp.this, "Account created successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
                    navigateToLogin();
                } catch (ExecutionException ex) {
                    if (ex.getCause() != null && ex.getCause() instanceof Exception) {
                         JOptionPane.showMessageDialog(SignUp.this, ex.getCause().getMessage(), "Sign Up Failed", JOptionPane.ERROR_MESSAGE);
                    } else {
                        logger.log(java.util.logging.Level.SEVERE, "Sign up error", ex);
                        JOptionPane.showMessageDialog(SignUp.this, "Error creating account: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    }
                } catch (InterruptedException ex) {
                    logger.log(java.util.logging.Level.SEVERE, "Sign up interrupted", ex);
                }
            }
        };
        worker.execute();
    }
    
    private void navigateToLogin() {
        this.dispose(); 
        new Login().setVisible(true); 
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new SignUp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField ConfirmPasswordText;
    private javax.swing.JLabel bgImage;
    private javax.swing.JTextField emailText;
    private javax.swing.JLabel goToLogin;
    private javax.swing.JLabel heading;
    private javax.swing.JLabel logo;
    private javax.swing.JPasswordField passwordText;
    private javax.swing.JButton signUpButton;
    private javax.swing.JPanel signUpPanel;
    private javax.swing.JTextField usernameText;
    // End of variables declaration//GEN-END:variables
}
